//! ps's tables (procps-ng 4.0.2 src/ps/output.c): every format specifier with its
//! header, print function, sort item, width and flags; the macros that stand for lists
//! of them; AIX's field descriptors; and the one-letter sort keys.

/// How a column is justified (common.h CF_JUST_MASK), and when it prints.
pub(super) const CF_JUST_MASK: u32 = 0x0f;
pub(super) const USER: u32 = 1;
pub(super) const LEFT: u32 = 2;
pub(super) const RIGHT: u32 = 3;
pub(super) const UNLIMITED: u32 = 4;
pub(super) const WCHAN: u32 = 5;
pub(super) const SIGNAL: u32 = 6;
pub(super) const PIDMAX: u32 = 0x10;
const TO: u32 = 0x1000_0000;
const PO: u32 = 0x2000_0000;
const ET: u32 = 0x4000_0000;
const AN: u32 = 0x8000_0000;

/// A format specifier (format_struct; its vendor, used only by a check whose result
/// parser.c ignores, is left out).
#[derive(Debug)]
pub(super) struct Spec {
    pub spec: &'static str,
    pub head: &'static str,
    pub pr: Pr,
    pub sr: Sr,
    pub width: i32,
    pub flags: u32,
}

/// A column's print function (output.c's pr_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum Pr {
    Agid,
    Agnice,
    Args,
    Bsdstart,
    Bsdtime,
    C,
    Cgname,
    Cgroup,
    Cgroupns,
    Class,
    Comm,
    Context,
    Cp,
    Drs,
    Dsiz,
    Egid,
    Egroup,
    Eip,
    Esp,
    Etime,
    Etimes,
    Euid,
    Euser,
    Exe,
    Fgid,
    Fgroup,
    Flag,
    Fname,
    Fuid,
    Fuser,
    Ipcns,
    Lim,
    Lstart,
    Luid,
    Lxcname,
    Majflt,
    Minflt,
    Mntns,
    Netns,
    Nice,
    Nlwp,
    Nop,
    Numa,
    Oom,
    OomAdj,
    Opri,
    Pcpu,
    Pgid,
    Pidns,
    Pmem,
    Ppid,
    Pri,
    PriApi,
    PriBar,
    PriBaz,
    PriFoo,
    Priority,
    Procs,
    Psr,
    Pss,
    Rbytes,
    Rchars,
    Rgid,
    Rgroup,
    Rops,
    Rss,
    Rtprio,
    Ruid,
    Ruser,
    S,
    Sched,
    SdMachine,
    SdOuid,
    SdSeat,
    SdSession,
    SdSlice,
    SdUnit,
    SdUunit,
    Sess,
    SgiP,
    Sgid,
    Sgroup,
    Sig,
    Sigcatch,
    Sigignore,
    Sigmask,
    Size,
    Stackp,
    Start,
    Stat,
    Stime,
    Suid,
    Supgid,
    Supgrp,
    Suser,
    Swapable,
    Sz,
    TLeft,
    TLeft2,
    TRight,
    TRight2,
    TUnlimited,
    TUnlimited2,
    Tasks,
    Time,
    Timens,
    Times,
    Tpgid,
    Trs,
    Tsig,
    Tsiz,
    Tty4,
    Tty8,
    Userns,
    Uss,
    Utilization,
    UtilizationC,
    Utsns,
    Vsz,
    Wbytes,
    Wcbytes,
    Wchan,
    Wchars,
    Wops,
}

/// A <pids> item a column sorts by (library/pids.h's PIDS_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum Sr {
    AddrCodeEnd,
    AddrCodeStart,
    AddrCurrEip,
    AddrCurrEsp,
    AddrStackStart,
    AutogrpId,
    AutogrpNice,
    Cgname,
    Cgroup,
    Cmd,
    Cmdline,
    Exe,
    Flags,
    FltMaj,
    FltMin,
    IdEgid,
    IdEgroup,
    IdEuid,
    IdEuser,
    IdFgid,
    IdFgroup,
    IdFuid,
    IdFuser,
    IdLogin,
    IdPgrp,
    IdPid,
    IdPpid,
    IdRgid,
    IdRgroup,
    IdRuid,
    IdRuser,
    IdSession,
    IdSgid,
    IdSgroup,
    IdSuid,
    IdSuser,
    IdTgid,
    IdTpgid,
    IoReadBytes,
    IoReadChars,
    IoReadOps,
    IoWriteBytes,
    IoWriteCbytes,
    IoWriteChars,
    IoWriteOps,
    Lxcname,
    MemResPgs,
    MemShrPgs,
    Nice,
    Nlwp,
    NsCgroup,
    NsIpc,
    NsMnt,
    NsNet,
    NsPid,
    NsTime,
    NsUser,
    NsUts,
    OomAdj,
    OomScore,
    Priority,
    PriorityRt,
    Processor,
    ProcessorNode,
    RssRlim,
    SchedClass,
    SdMach,
    SdOuid,
    SdSeat,
    SdSess,
    SdSlice,
    SdUnit,
    SdUunit,
    Sigblocked,
    Sigcatch,
    Sigignore,
    Signals,
    Sigpending,
    SmapPrvTotal,
    SmapPss,
    State,
    Supgids,
    Supgroups,
    TicsAll,
    TicsBegan,
    TicsUser,
    TicsUserC,
    TimeAll,
    TimeElapsed,
    TtyName,
    Utilization,
    UtilizationC,
    VmData,
    VmExe,
    VmLib,
    VmRss,
    VmRssLocked,
    VmSize,
    VmStack,
    VsizeBytes,
    WchanName,
    Noop,
}

/// format_array, in its order.
pub(super) const SPECS: &[Spec] = &[
    Spec {
        spec: "%cpu",
        head: "%CPU",
        pr: Pr::Pcpu,
        sr: Sr::Utilization,
        width: 4,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "%mem",
        head: "%MEM",
        pr: Pr::Pmem,
        sr: Sr::VmRss,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "_left",
        head: "LLLLLLLL",
        pr: Pr::TLeft,
        sr: Sr::Noop,
        width: 8,
        flags: ET | LEFT,
    },
    Spec {
        spec: "_left2",
        head: "L2L2L2L2",
        pr: Pr::TLeft2,
        sr: Sr::Noop,
        width: 8,
        flags: ET | LEFT,
    },
    Spec {
        spec: "_right",
        head: "RRRRRRRRRRR",
        pr: Pr::TRight,
        sr: Sr::Noop,
        width: 11,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "_right2",
        head: "R2R2R2R2R2R",
        pr: Pr::TRight2,
        sr: Sr::Noop,
        width: 11,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "_unlimited",
        head: "U",
        pr: Pr::TUnlimited,
        sr: Sr::Noop,
        width: 16,
        flags: ET | UNLIMITED,
    },
    Spec {
        spec: "_unlimited2",
        head: "U2",
        pr: Pr::TUnlimited2,
        sr: Sr::Noop,
        width: 16,
        flags: ET | UNLIMITED,
    },
    Spec {
        spec: "acflag",
        head: "ACFLG",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "acflg",
        head: "ACFLG",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "addr",
        head: "ADDR",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "addr_1",
        head: "ADDR",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: AN | LEFT,
    },
    Spec {
        spec: "ag_id",
        head: "AGID",
        pr: Pr::Agid,
        sr: Sr::AutogrpId,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "ag_nice",
        head: "AGNI",
        pr: Pr::Agnice,
        sr: Sr::AutogrpNice,
        width: 4,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "alarm",
        head: "ALARM",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "argc",
        head: "ARGC",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "args",
        head: "COMMAND",
        pr: Pr::Args,
        sr: Sr::Cmdline,
        width: 27,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "atime",
        head: "TIME",
        pr: Pr::Time,
        sr: Sr::TimeAll,
        width: 8,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "blocked",
        head: "BLOCKED",
        pr: Pr::Sigmask,
        sr: Sr::Sigblocked,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "bnd",
        head: "BND",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "bsdstart",
        head: "START",
        pr: Pr::Bsdstart,
        sr: Sr::TicsBegan,
        width: 6,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "bsdtime",
        head: "TIME",
        pr: Pr::Bsdtime,
        sr: Sr::TicsAll,
        width: 6,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "c",
        head: "C",
        pr: Pr::C,
        sr: Sr::Utilization,
        width: 2,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "caught",
        head: "CAUGHT",
        pr: Pr::Sigcatch,
        sr: Sr::Sigcatch,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "cgname",
        head: "CGNAME",
        pr: Pr::Cgname,
        sr: Sr::Cgname,
        width: 27,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "cgroup",
        head: "CGROUP",
        pr: Pr::Cgroup,
        sr: Sr::Cgroup,
        width: 27,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "cgroupns",
        head: "CGROUPNS",
        pr: Pr::Cgroupns,
        sr: Sr::NsCgroup,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "class",
        head: "CLS",
        pr: Pr::Class,
        sr: Sr::SchedClass,
        width: 3,
        flags: TO | LEFT,
    },
    Spec {
        spec: "cls",
        head: "CLS",
        pr: Pr::Class,
        sr: Sr::SchedClass,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "cmaj_flt",
        head: "-",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "cmd",
        head: "CMD",
        pr: Pr::Args,
        sr: Sr::Cmdline,
        width: 27,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "cmin_flt",
        head: "-",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "cnswap",
        head: "-",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "comm",
        head: "COMMAND",
        pr: Pr::Comm,
        sr: Sr::Cmd,
        width: 15,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "command",
        head: "COMMAND",
        pr: Pr::Args,
        sr: Sr::Cmdline,
        width: 27,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "context",
        head: "CONTEXT",
        pr: Pr::Context,
        sr: Sr::IdTgid,
        width: 31,
        flags: ET | LEFT,
    },
    Spec {
        spec: "cp",
        head: "CP",
        pr: Pr::Cp,
        sr: Sr::Utilization,
        width: 3,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "cpu",
        head: "CPU",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 3,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "cpuid",
        head: "CPUID",
        pr: Pr::Psr,
        sr: Sr::Processor,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "cputime",
        head: "TIME",
        pr: Pr::Time,
        sr: Sr::TimeAll,
        width: 8,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "cputimes",
        head: "TIME",
        pr: Pr::Times,
        sr: Sr::TimeAll,
        width: 8,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "ctid",
        head: "CTID",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "cuc",
        head: "%CUC",
        pr: Pr::UtilizationC,
        sr: Sr::UtilizationC,
        width: 7,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "cursig",
        head: "CURSIG",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "cutime",
        head: "-",
        pr: Pr::Nop,
        sr: Sr::TicsUserC,
        width: 1,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "cuu",
        head: "%CUU",
        pr: Pr::Utilization,
        sr: Sr::Utilization,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "cwd",
        head: "CWD",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 3,
        flags: AN | LEFT,
    },
    Spec {
        spec: "drs",
        head: "DRS",
        pr: Pr::Drs,
        sr: Sr::VsizeBytes,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "dsiz",
        head: "DSIZ",
        pr: Pr::Dsiz,
        sr: Sr::VsizeBytes,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "egid",
        head: "EGID",
        pr: Pr::Egid,
        sr: Sr::IdEgid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "egroup",
        head: "EGROUP",
        pr: Pr::Egroup,
        sr: Sr::IdEgroup,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "eip",
        head: "EIP",
        pr: Pr::Eip,
        sr: Sr::AddrCurrEip,
        width: 16,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "emul",
        head: "EMUL",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 13,
        flags: PO | LEFT,
    },
    Spec {
        spec: "end_code",
        head: "E_CODE",
        pr: Pr::Nop,
        sr: Sr::AddrCodeEnd,
        width: 16,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "environ",
        head: "ENVIRONMENT",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 11,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "esp",
        head: "ESP",
        pr: Pr::Esp,
        sr: Sr::AddrCurrEsp,
        width: 16,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "etime",
        head: "ELAPSED",
        pr: Pr::Etime,
        sr: Sr::TimeElapsed,
        width: 11,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "etimes",
        head: "ELAPSED",
        pr: Pr::Etimes,
        sr: Sr::TimeElapsed,
        width: 7,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "euid",
        head: "EUID",
        pr: Pr::Euid,
        sr: Sr::IdEuid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "euser",
        head: "EUSER",
        pr: Pr::Euser,
        sr: Sr::IdEuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "exe",
        head: "EXE",
        pr: Pr::Exe,
        sr: Sr::Exe,
        width: 27,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "f",
        head: "F",
        pr: Pr::Flag,
        sr: Sr::Flags,
        width: 1,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "fgid",
        head: "FGID",
        pr: Pr::Fgid,
        sr: Sr::Flags,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "fgroup",
        head: "FGROUP",
        pr: Pr::Fgroup,
        sr: Sr::IdFgroup,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "flag",
        head: "F",
        pr: Pr::Flag,
        sr: Sr::Flags,
        width: 1,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "flags",
        head: "F",
        pr: Pr::Flag,
        sr: Sr::Flags,
        width: 1,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "fname",
        head: "COMMAND",
        pr: Pr::Fname,
        sr: Sr::Cmd,
        width: 8,
        flags: PO | LEFT,
    },
    Spec {
        spec: "fsgid",
        head: "FSGID",
        pr: Pr::Fgid,
        sr: Sr::IdFgid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "fsgroup",
        head: "FSGROUP",
        pr: Pr::Fgroup,
        sr: Sr::IdFgroup,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "fsuid",
        head: "FSUID",
        pr: Pr::Fuid,
        sr: Sr::IdFuid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "fsuser",
        head: "FSUSER",
        pr: Pr::Fuser,
        sr: Sr::IdFuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "fuid",
        head: "FUID",
        pr: Pr::Fuid,
        sr: Sr::IdFuid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "fuser",
        head: "FUSER",
        pr: Pr::Fuser,
        sr: Sr::IdFuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "gid",
        head: "GID",
        pr: Pr::Egid,
        sr: Sr::IdEgid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "group",
        head: "GROUP",
        pr: Pr::Egroup,
        sr: Sr::IdEgroup,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "ignored",
        head: "IGNORED",
        pr: Pr::Sigignore,
        sr: Sr::Sigignore,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "inblk",
        head: "INBLK",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "inblock",
        head: "INBLK",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "intpri",
        head: "PRI",
        pr: Pr::Opri,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "ipcns",
        head: "IPCNS",
        pr: Pr::Ipcns,
        sr: Sr::NsIpc,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "jid",
        head: "JID",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "jobc",
        head: "JOBC",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "ktrace",
        head: "KTRACE",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 8,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "ktracep",
        head: "KTRACEP",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 8,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "label",
        head: "LABEL",
        pr: Pr::Context,
        sr: Sr::IdTgid,
        width: 31,
        flags: ET | LEFT,
    },
    Spec {
        spec: "lastcpu",
        head: "C",
        pr: Pr::Psr,
        sr: Sr::Processor,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "lim",
        head: "LIM",
        pr: Pr::Lim,
        sr: Sr::RssRlim,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "login",
        head: "LOGNAME",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 8,
        flags: AN | LEFT,
    },
    Spec {
        spec: "logname",
        head: "LOGNAME",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 8,
        flags: AN | LEFT,
    },
    Spec {
        spec: "longtname",
        head: "TTY",
        pr: Pr::Tty8,
        sr: Sr::TtyName,
        width: 8,
        flags: PO | LEFT,
    },
    Spec {
        spec: "lsession",
        head: "SESSION",
        pr: Pr::SdSession,
        sr: Sr::SdSess,
        width: 11,
        flags: ET | LEFT,
    },
    Spec {
        spec: "lstart",
        head: "STARTED",
        pr: Pr::Lstart,
        sr: Sr::TicsBegan,
        width: 24,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "luid",
        head: "LUID",
        pr: Pr::Luid,
        sr: Sr::IdLogin,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "luser",
        head: "LUSER",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "lwp",
        head: "LWP",
        pr: Pr::Tasks,
        sr: Sr::IdPid,
        width: 5,
        flags: TO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "lxc",
        head: "LXC",
        pr: Pr::Lxcname,
        sr: Sr::Lxcname,
        width: 8,
        flags: ET | LEFT,
    },
    Spec {
        spec: "m_drs",
        head: "DRS",
        pr: Pr::Drs,
        sr: Sr::VsizeBytes,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "m_dt",
        head: "DT",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "m_lrs",
        head: "LRS",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "m_resident",
        head: "RES",
        pr: Pr::Nop,
        sr: Sr::MemResPgs,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "m_share",
        head: "SHRD",
        pr: Pr::Nop,
        sr: Sr::MemShrPgs,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "m_size",
        head: "SIZE",
        pr: Pr::Size,
        sr: Sr::VsizeBytes,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "m_swap",
        head: "SWAP",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "m_trs",
        head: "TRS",
        pr: Pr::Trs,
        sr: Sr::VsizeBytes,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "machine",
        head: "MACHINE",
        pr: Pr::SdMachine,
        sr: Sr::SdMach,
        width: 31,
        flags: ET | LEFT,
    },
    Spec {
        spec: "maj_flt",
        head: "MAJFL",
        pr: Pr::Majflt,
        sr: Sr::FltMaj,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "majflt",
        head: "MAJFLT",
        pr: Pr::Majflt,
        sr: Sr::FltMaj,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "min_flt",
        head: "MINFL",
        pr: Pr::Minflt,
        sr: Sr::FltMin,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "minflt",
        head: "MINFLT",
        pr: Pr::Minflt,
        sr: Sr::FltMin,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "mntns",
        head: "MNTNS",
        pr: Pr::Mntns,
        sr: Sr::NsMnt,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "msgrcv",
        head: "MSGRCV",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "msgsnd",
        head: "MSGSND",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "mwchan",
        head: "MWCHAN",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: TO | WCHAN,
    },
    Spec {
        spec: "netns",
        head: "NETNS",
        pr: Pr::Netns,
        sr: Sr::NsNet,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "ni",
        head: "NI",
        pr: Pr::Nice,
        sr: Sr::Nice,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "nice",
        head: "NI",
        pr: Pr::Nice,
        sr: Sr::Nice,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "nivcsw",
        head: "IVCSW",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "nlwp",
        head: "NLWP",
        pr: Pr::Nlwp,
        sr: Sr::Nlwp,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "nsignals",
        head: "NSIGS",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "nsigs",
        head: "NSIGS",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "nswap",
        head: "NSWAP",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "numa",
        head: "NUMA",
        pr: Pr::Numa,
        sr: Sr::ProcessorNode,
        width: 4,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "nvcsw",
        head: "VCSW",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "nwchan",
        head: "WCHAN",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "oom",
        head: "OOM",
        pr: Pr::Oom,
        sr: Sr::OomScore,
        width: 4,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "oomadj",
        head: "OOMADJ",
        pr: Pr::OomAdj,
        sr: Sr::OomAdj,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "opri",
        head: "PRI",
        pr: Pr::Opri,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "osz",
        head: "SZ",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 2,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "oublk",
        head: "OUBLK",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "oublock",
        head: "OUBLK",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "ouid",
        head: "OWNER",
        pr: Pr::SdOuid,
        sr: Sr::SdOuid,
        width: 5,
        flags: ET | LEFT,
    },
    Spec {
        spec: "p_ru",
        head: "P_RU",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "paddr",
        head: "PADDR",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "pagein",
        head: "PAGEIN",
        pr: Pr::Majflt,
        sr: Sr::FltMaj,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "pcpu",
        head: "%CPU",
        pr: Pr::Pcpu,
        sr: Sr::Utilization,
        width: 4,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "pending",
        head: "PENDING",
        pr: Pr::Sig,
        sr: Sr::Signals,
        width: 9,
        flags: ET | SIGNAL,
    },
    Spec {
        spec: "pgid",
        head: "PGID",
        pr: Pr::Pgid,
        sr: Sr::IdPgrp,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "pgrp",
        head: "PGRP",
        pr: Pr::Pgid,
        sr: Sr::IdPgrp,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "pid",
        head: "PID",
        pr: Pr::Procs,
        sr: Sr::IdTgid,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "pidns",
        head: "PIDNS",
        pr: Pr::Pidns,
        sr: Sr::NsPid,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "pmem",
        head: "%MEM",
        pr: Pr::Pmem,
        sr: Sr::VmRss,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "poip",
        head: "-",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "policy",
        head: "POL",
        pr: Pr::Class,
        sr: Sr::SchedClass,
        width: 3,
        flags: TO | LEFT,
    },
    Spec {
        spec: "ppid",
        head: "PPID",
        pr: Pr::Ppid,
        sr: Sr::IdPpid,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "pri",
        head: "PRI",
        pr: Pr::Pri,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "pri_api",
        head: "API",
        pr: Pr::PriApi,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "pri_bar",
        head: "BAR",
        pr: Pr::PriBar,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "pri_baz",
        head: "BAZ",
        pr: Pr::PriBaz,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "pri_foo",
        head: "FOO",
        pr: Pr::PriFoo,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "priority",
        head: "PRI",
        pr: Pr::Priority,
        sr: Sr::Priority,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "prmgrp",
        head: "PRMGRP",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 12,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "prmid",
        head: "PRMID",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 12,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "project",
        head: "PROJECT",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 12,
        flags: PO | LEFT,
    },
    Spec {
        spec: "projid",
        head: "PROJID",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "pset",
        head: "PSET",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "psr",
        head: "PSR",
        pr: Pr::Psr,
        sr: Sr::Processor,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "pss",
        head: "PSS",
        pr: Pr::Pss,
        sr: Sr::SmapPss,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "psxpri",
        head: "PPR",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "rbytes",
        head: "RBYTES",
        pr: Pr::Rbytes,
        sr: Sr::IoReadBytes,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "rchars",
        head: "RCHARS",
        pr: Pr::Rchars,
        sr: Sr::IoReadChars,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "re",
        head: "RE",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 3,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "resident",
        head: "RES",
        pr: Pr::Nop,
        sr: Sr::MemResPgs,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "rgid",
        head: "RGID",
        pr: Pr::Rgid,
        sr: Sr::IdRgid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "rgroup",
        head: "RGROUP",
        pr: Pr::Rgroup,
        sr: Sr::IdRgroup,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "rlink",
        head: "RLINK",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 8,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "rops",
        head: "ROPS",
        pr: Pr::Rops,
        sr: Sr::IoReadOps,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "rss",
        head: "RSS",
        pr: Pr::Rss,
        sr: Sr::VmRss,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "rssize",
        head: "RSS",
        pr: Pr::Rss,
        sr: Sr::VmRss,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "rsz",
        head: "RSZ",
        pr: Pr::Rss,
        sr: Sr::VmRss,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "rtprio",
        head: "RTPRIO",
        pr: Pr::Rtprio,
        sr: Sr::PriorityRt,
        width: 6,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "ruid",
        head: "RUID",
        pr: Pr::Ruid,
        sr: Sr::IdRuid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "ruser",
        head: "RUSER",
        pr: Pr::Ruser,
        sr: Sr::IdRuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "s",
        head: "S",
        pr: Pr::S,
        sr: Sr::State,
        width: 1,
        flags: TO | LEFT,
    },
    Spec {
        spec: "sched",
        head: "SCH",
        pr: Pr::Sched,
        sr: Sr::SchedClass,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "scnt",
        head: "SCNT",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "scount",
        head: "SC",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "seat",
        head: "SEAT",
        pr: Pr::SdSeat,
        sr: Sr::SdSeat,
        width: 11,
        flags: ET | LEFT,
    },
    Spec {
        spec: "sess",
        head: "SESS",
        pr: Pr::Sess,
        sr: Sr::IdSession,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "session",
        head: "SESS",
        pr: Pr::Sess,
        sr: Sr::IdSession,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "sgi_p",
        head: "P",
        pr: Pr::SgiP,
        sr: Sr::State,
        width: 1,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "sgi_rss",
        head: "RSS",
        pr: Pr::Rss,
        sr: Sr::VmRss,
        width: 4,
        flags: PO | LEFT,
    },
    Spec {
        spec: "sgid",
        head: "SGID",
        pr: Pr::Sgid,
        sr: Sr::IdSgid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "sgroup",
        head: "SGROUP",
        pr: Pr::Sgroup,
        sr: Sr::IdSgroup,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "share",
        head: "-",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "sid",
        head: "SID",
        pr: Pr::Sess,
        sr: Sr::IdSession,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "sig",
        head: "PENDING",
        pr: Pr::Sig,
        sr: Sr::Signals,
        width: 9,
        flags: ET | SIGNAL,
    },
    Spec {
        spec: "sig_block",
        head: "BLOCKED",
        pr: Pr::Sigmask,
        sr: Sr::Sigblocked,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "sig_catch",
        head: "CATCHED",
        pr: Pr::Sigcatch,
        sr: Sr::Sigcatch,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "sig_ignore",
        head: "IGNORED",
        pr: Pr::Sigignore,
        sr: Sr::Sigignore,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "sig_pend",
        head: "SIGNAL",
        pr: Pr::Sig,
        sr: Sr::Signals,
        width: 9,
        flags: ET | SIGNAL,
    },
    Spec {
        spec: "sigcatch",
        head: "CAUGHT",
        pr: Pr::Sigcatch,
        sr: Sr::Sigcatch,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "sigignore",
        head: "IGNORED",
        pr: Pr::Sigignore,
        sr: Sr::Sigignore,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "sigmask",
        head: "BLOCKED",
        pr: Pr::Sigmask,
        sr: Sr::Sigblocked,
        width: 9,
        flags: TO | SIGNAL,
    },
    Spec {
        spec: "size",
        head: "SIZE",
        pr: Pr::Swapable,
        sr: Sr::VsizeBytes,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "sl",
        head: "SL",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 3,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "slice",
        head: "SLICE",
        pr: Pr::SdSlice,
        sr: Sr::SdSlice,
        width: 31,
        flags: ET | LEFT,
    },
    Spec {
        spec: "spid",
        head: "SPID",
        pr: Pr::Tasks,
        sr: Sr::IdPid,
        width: 5,
        flags: TO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "stackp",
        head: "STACKP",
        pr: Pr::Stackp,
        sr: Sr::AddrStackStart,
        width: 16,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "start",
        head: "STARTED",
        pr: Pr::Start,
        sr: Sr::TicsBegan,
        width: 8,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "start_code",
        head: "S_CODE",
        pr: Pr::Nop,
        sr: Sr::AddrCodeStart,
        width: 16,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "start_stack",
        head: "STACKP",
        pr: Pr::Stackp,
        sr: Sr::AddrStackStart,
        width: 16,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "start_time",
        head: "START",
        pr: Pr::Stime,
        sr: Sr::TicsBegan,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "stat",
        head: "STAT",
        pr: Pr::Stat,
        sr: Sr::State,
        width: 4,
        flags: TO | LEFT,
    },
    Spec {
        spec: "state",
        head: "S",
        pr: Pr::S,
        sr: Sr::State,
        width: 1,
        flags: TO | LEFT,
    },
    Spec {
        spec: "status",
        head: "STATUS",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "stime",
        head: "STIME",
        pr: Pr::Stime,
        sr: Sr::TicsBegan,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "suid",
        head: "SUID",
        pr: Pr::Suid,
        sr: Sr::IdSuid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "supgid",
        head: "SUPGID",
        pr: Pr::Supgid,
        sr: Sr::Supgids,
        width: 20,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "supgrp",
        head: "SUPGRP",
        pr: Pr::Supgrp,
        sr: Sr::Supgroups,
        width: 40,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "suser",
        head: "SUSER",
        pr: Pr::Suser,
        sr: Sr::IdSuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "svgid",
        head: "SVGID",
        pr: Pr::Sgid,
        sr: Sr::IdSgid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "svgroup",
        head: "SVGROUP",
        pr: Pr::Sgroup,
        sr: Sr::IdSgroup,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "svuid",
        head: "SVUID",
        pr: Pr::Suid,
        sr: Sr::IdSuid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "svuser",
        head: "SVUSER",
        pr: Pr::Suser,
        sr: Sr::IdSuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "systime",
        head: "SYSTEM",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "sz",
        head: "SZ",
        pr: Pr::Sz,
        sr: Sr::VmSize,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "taskid",
        head: "TASKID",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: TO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "tdev",
        head: "TDEV",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "tgid",
        head: "TGID",
        pr: Pr::Procs,
        sr: Sr::IdTgid,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "thcount",
        head: "THCNT",
        pr: Pr::Nlwp,
        sr: Sr::Nlwp,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "tid",
        head: "TID",
        pr: Pr::Tasks,
        sr: Sr::IdPid,
        width: 5,
        flags: TO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "time",
        head: "TIME",
        pr: Pr::Time,
        sr: Sr::TimeAll,
        width: 8,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "timens",
        head: "TIMENS",
        pr: Pr::Timens,
        sr: Sr::NsTime,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "timeout",
        head: "TMOUT",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "times",
        head: "TIME",
        pr: Pr::Times,
        sr: Sr::TimeAll,
        width: 8,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "tmout",
        head: "TMOUT",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "tname",
        head: "TTY",
        pr: Pr::Tty8,
        sr: Sr::TtyName,
        width: 8,
        flags: PO | LEFT,
    },
    Spec {
        spec: "tpgid",
        head: "TPGID",
        pr: Pr::Tpgid,
        sr: Sr::IdTpgid,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "trs",
        head: "TRS",
        pr: Pr::Trs,
        sr: Sr::VsizeBytes,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "trss",
        head: "TRSS",
        pr: Pr::Trs,
        sr: Sr::VsizeBytes,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "tsess",
        head: "TSESS",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "tsession",
        head: "TSESS",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "tsid",
        head: "TSID",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: PO | PIDMAX | RIGHT,
    },
    Spec {
        spec: "tsig",
        head: "PENDING",
        pr: Pr::Tsig,
        sr: Sr::Sigpending,
        width: 9,
        flags: ET | SIGNAL,
    },
    Spec {
        spec: "tsiz",
        head: "TSIZ",
        pr: Pr::Tsiz,
        sr: Sr::VsizeBytes,
        width: 4,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "tt",
        head: "TT",
        pr: Pr::Tty8,
        sr: Sr::TtyName,
        width: 8,
        flags: PO | LEFT,
    },
    Spec {
        spec: "tty",
        head: "TT",
        pr: Pr::Tty8,
        sr: Sr::TtyName,
        width: 8,
        flags: PO | LEFT,
    },
    Spec {
        spec: "tty4",
        head: "TTY",
        pr: Pr::Tty4,
        sr: Sr::TtyName,
        width: 4,
        flags: PO | LEFT,
    },
    Spec {
        spec: "tty8",
        head: "TTY",
        pr: Pr::Tty8,
        sr: Sr::TtyName,
        width: 8,
        flags: PO | LEFT,
    },
    Spec {
        spec: "u_procp",
        head: "UPROCP",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 6,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "ucmd",
        head: "CMD",
        pr: Pr::Comm,
        sr: Sr::Cmd,
        width: 15,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "ucomm",
        head: "COMMAND",
        pr: Pr::Comm,
        sr: Sr::Cmd,
        width: 15,
        flags: PO | UNLIMITED,
    },
    Spec {
        spec: "uid",
        head: "UID",
        pr: Pr::Euid,
        sr: Sr::IdEuid,
        width: 5,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "uid_hack",
        head: "UID",
        pr: Pr::Euser,
        sr: Sr::IdEuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "umask",
        head: "UMASK",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "uname",
        head: "USER",
        pr: Pr::Euser,
        sr: Sr::IdEuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "unit",
        head: "UNIT",
        pr: Pr::SdUnit,
        sr: Sr::SdUnit,
        width: 31,
        flags: ET | LEFT,
    },
    Spec {
        spec: "upr",
        head: "UPR",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "uprocp",
        head: "UPROCP",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 8,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "user",
        head: "USER",
        pr: Pr::Euser,
        sr: Sr::IdEuser,
        width: 8,
        flags: ET | USER,
    },
    Spec {
        spec: "userns",
        head: "USERNS",
        pr: Pr::Userns,
        sr: Sr::NsUser,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "usertime",
        head: "USER",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 4,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "usrpri",
        head: "UPR",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 3,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "uss",
        head: "USS",
        pr: Pr::Uss,
        sr: Sr::SmapPrvTotal,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "util",
        head: "C",
        pr: Pr::C,
        sr: Sr::Utilization,
        width: 2,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "utime",
        head: "UTIME",
        pr: Pr::Nop,
        sr: Sr::TicsUser,
        width: 6,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "utsns",
        head: "UTSNS",
        pr: Pr::Utsns,
        sr: Sr::NsUts,
        width: 10,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "uunit",
        head: "UUNIT",
        pr: Pr::SdUunit,
        sr: Sr::SdUunit,
        width: 31,
        flags: ET | LEFT,
    },
    Spec {
        spec: "vm_data",
        head: "DATA",
        pr: Pr::Nop,
        sr: Sr::VmData,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "vm_exe",
        head: "EXE",
        pr: Pr::Nop,
        sr: Sr::VmExe,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "vm_lib",
        head: "LIB",
        pr: Pr::Nop,
        sr: Sr::VmLib,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "vm_lock",
        head: "LCK",
        pr: Pr::Nop,
        sr: Sr::VmRssLocked,
        width: 3,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "vm_stack",
        head: "STACK",
        pr: Pr::Nop,
        sr: Sr::VmStack,
        width: 5,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "vsize",
        head: "VSZ",
        pr: Pr::Vsz,
        sr: Sr::VsizeBytes,
        width: 6,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "vsz",
        head: "VSZ",
        pr: Pr::Vsz,
        sr: Sr::VmSize,
        width: 6,
        flags: PO | RIGHT,
    },
    Spec {
        spec: "wbytes",
        head: "WBYTES",
        pr: Pr::Wbytes,
        sr: Sr::IoWriteBytes,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "wcbytes",
        head: "WCBYTES",
        pr: Pr::Wcbytes,
        sr: Sr::IoWriteCbytes,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "wchan",
        head: "WCHAN",
        pr: Pr::Wchan,
        sr: Sr::WchanName,
        width: 6,
        flags: TO | WCHAN,
    },
    Spec {
        spec: "wchars",
        head: "WCHARS",
        pr: Pr::Wchars,
        sr: Sr::IoWriteChars,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "wname",
        head: "WCHAN",
        pr: Pr::Wchan,
        sr: Sr::WchanName,
        width: 6,
        flags: TO | WCHAN,
    },
    Spec {
        spec: "wops",
        head: "WOPS",
        pr: Pr::Wops,
        sr: Sr::IoWriteOps,
        width: 5,
        flags: TO | RIGHT,
    },
    Spec {
        spec: "xstat",
        head: "XSTAT",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 5,
        flags: AN | RIGHT,
    },
    Spec {
        spec: "zone",
        head: "ZONE",
        pr: Pr::Context,
        sr: Sr::IdTgid,
        width: 31,
        flags: ET | LEFT,
    },
    Spec {
        spec: "zoneid",
        head: "ZONEID",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 31,
        flags: ET | RIGHT,
    },
    Spec {
        spec: "~",
        head: "-",
        pr: Pr::Nop,
        sr: Sr::Noop,
        width: 1,
        flags: AN | RIGHT,
    },
];

/// macro_array: names for lists of specifiers.
pub(super) const MACROS: &[(&str, &str)] = &[
    ("DFMT", "pid,tname,state,cputime,cmd"),
    ("DefBSD", "pid,tname,stat,bsdtime,args"),
    ("DefSysV", "pid,tname,time,cmd"),
    ("END_BSD", "state,tname,cputime,comm"),
    ("END_SYS5", "state,tname,time,command"),
    ("F5FMT", "uname,pid,ppid,c,start,tname,time,cmd"),
    ("FB_", "pid,tt,stat,time,command"),
    ("FB_j", "user,pid,ppid,pgid,sess,jobc,stat,tt,time,command"),
    (
        "FB_l",
        "uid,pid,ppid,cpu,pri,nice,vsz,rss,wchan,stat,tt,time,command",
    ),
    ("FB_u", "user,pid,pcpu,pmem,vsz,rss,tt,stat,start,time,command"),
    (
        "FB_v",
        "pid,stat,time,sl,re,pagein,vsz,rss,lim,tsiz,pcpu,pmem,command",
    ),
    ("FD_", "pid,tty,time,comm"),
    ("FD_f", "user,pid,ppid,start_time,tty,time,comm"),
    ("FD_fj", "user,pid,ppid,start_time,tty,time,pgid,sid,comm"),
    ("FD_j", "pid,tty,time,pgid,sid,comm"),
    (
        "FD_l",
        "flags,state,uid,pid,ppid,priority,nice,vsz,wchan,tty,time,comm",
    ),
    (
        "FD_lj",
        "flags,state,uid,pid,ppid,priority,nice,vsz,wchan,tty,time,pgid,sid,comm",
    ),
    (
        "FL5FMT",
        "f,state,uid,pid,ppid,pcpu,pri,nice,rss,wchan,start,time,command",
    ),
    ("FLASK_context", "pid,context,command"),
    ("HP_", "pid,tty,time,comm"),
    ("HP_f", "user,pid,ppid,cpu,stime,tty,time,args"),
    (
        "HP_fl",
        "flags,state,user,pid,ppid,cpu,intpri,nice,addr,sz,wchan,stime,tty,time,args",
    ),
    (
        "HP_l",
        "flags,state,uid,pid,ppid,cpu,intpri,nice,addr,sz,wchan,tty,time,comm",
    ),
    ("J390", "pid,sid,pgrp,tname,atime,args"),
    ("JFMT", "user,pid,ppid,pgid,sess,jobc,state,tname,cputime,command"),
    (
        "L5FMT",
        "f,state,uid,pid,ppid,c,pri,nice,addr,sz,wchan,tt,time,ucmd",
    ),
    (
        "LFMT",
        "uid,pid,ppid,cp,pri,nice,vsz,rss,wchan,state,tname,cputime,command",
    ),
    (
        "OL_X",
        "pid,start_stack,esp,eip,timeout,alarm,stat,tname,bsdtime,args",
    ),
    ("OL_j", "ppid,pid,pgid,sid,tname,tpgid,stat,uid,bsdtime,args"),
    (
        "OL_l",
        "flags,uid,pid,ppid,priority,nice,vsz,rss,wchan,stat,tname,bsdtime,args",
    ),
    (
        "OL_m",
        "pid,tname,majflt,minflt,m_trs,m_drs,m_size,m_swap,rss,m_share,vm_lib,m_dt,args",
    ),
    (
        "OL_s",
        "uid,pid,pending,sig_block,sig_ignore,caught,stat,tname,bsdtime,args",
    ),
    (
        "OL_u",
        "user,pid,pcpu,pmem,vsz,rss,tname,stat,start_time,bsdtime,args",
    ),
    ("OL_v", "pid,tname,stat,bsdtime,maj_flt,m_trs,m_drs,rss,pmem,args"),
    ("RD_", "pid,tname,state,bsdtime,comm"),
    ("RD_f", "uid,pid,ppid,start_time,tname,bsdtime,args"),
    ("RD_fj", "uid,pid,ppid,start_time,tname,bsdtime,pgid,sid,args"),
    ("RD_j", "pid,tname,state,bsdtime,pgid,sid,comm"),
    (
        "RD_l",
        "flags,state,uid,pid,ppid,priority,nice,wchan,tname,bsdtime,comm",
    ),
    (
        "RD_lj",
        "flags,state,uid,pid,ppid,priority,nice,wchan,tname,bsdtime,pgid,sid,comm",
    ),
    (
        "RUSAGE",
        "minflt,majflt,nswap,inblock,oublock,msgsnd,msgrcv,nsigs,nvcsw,nivcsw",
    ),
    ("SCHED", "user,pcpu,pri,usrpri,nice,psxpri,psr,policy,pset"),
    (
        "SFMT",
        "uid,pid,cursig,sig,sigmask,sigignore,sigcatch,stat,tname,command",
    ),
    ("Std_f", "uid_hack,pid,ppid,c,stime,tname,time,cmd"),
    (
        "Std_fl",
        "f,s,uid_hack,pid,ppid,c,opri,ni,addr,sz,wchan,stime,tname,time,cmd",
    ),
    (
        "Std_l",
        "f,s,uid,pid,ppid,c,opri,ni,addr,sz,wchan,tname,time,ucmd",
    ),
    ("THREAD", "user,pcpu,pri,scnt,wchan,usertime,systime"),
    ("UFMT", "uname,pid,pcpu,pmem,vsz,rss,tt,state,start,time,command"),
    ("VFMT", "pid,tt,state,time,sl,pagein,vsz,rss,pcpu,pmem,command"),
];

/// aix_array: AIX's `%` field descriptors, their specifiers and headers.
pub(super) const AIX: &[(u8, &str, &str)] = &[
    (b'C', "pcpu", "%CPU"),
    (b'G', "group", "GROUP"),
    (b'P', "ppid", "PPID"),
    (b'U', "user", "USER"),
    (b'a', "args", "COMMAND"),
    (b'c', "comm", "COMMAND"),
    (b'g', "rgroup", "RGROUP"),
    (b'n', "nice", "NI"),
    (b'p', "pid", "PID"),
    (b'r', "pgid", "PGID"),
    (b't', "etime", "ELAPSED"),
    (b'u', "ruser", "RUSER"),
    (b'x', "time", "TIME"),
    (b'y', "tty", "TTY"),
    (b'z', "vsz", "VSZ"),
];

/// shortsort_array: the one-letter sort keys of `O`.
pub(super) const SHORTSORT: &[(u8, &str)] = &[
    (b'C', "pcpu"),
    (b'G', "tpgid"),
    (b'J', "cstime"),
    (b'M', "maj_flt"),
    (b'N', "cmaj_flt"),
    (b'P', "ppid"),
    (b'R', "resident"),
    (b'S', "share"),
    (b'T', "start_time"),
    (b'U', "uid"),
    (b'c', "cmd"),
    (b'f', "flags"),
    (b'g', "pgrp"),
    (b'j', "cutime"),
    (b'k', "utime"),
    (b'm', "min_flt"),
    (b'n', "cmin_flt"),
    (b'o', "session"),
    (b'p', "pid"),
    (b'r', "rss"),
    (b's', "size"),
    (b't', "tty"),
    (b'u', "user"),
    (b'v', "vsize"),
    (b'y', "priority"),
];

/// The items finalize_stacks (display.c) fetches whatever the columns.
pub(super) const BASE_ITEMS: &[Sr] = &[
    Sr::Cmd,
    Sr::IdEgid,
    Sr::IdEuid,
    Sr::IdFgid,
    Sr::IdFuid,
    Sr::IdPid,
    Sr::IdPpid,
    Sr::IdRgid,
    Sr::IdRuid,
    Sr::IdSession,
    Sr::IdSgid,
    Sr::IdSuid,
    Sr::IdTgid,
    Sr::State,
    Sr::IdPgrp,
    Sr::IdTpgid,
    Sr::Nice,
    Sr::Nlwp,
    Sr::VmRssLocked,
    Sr::Sigblocked,
    Sr::Sigcatch,
    Sr::Sigignore,
    Sr::Signals,
    Sr::Sigpending,
    Sr::TicsAll,
    Sr::TimeAll,
    Sr::TimeElapsed,
    Sr::TicsBegan,
    Sr::Noop,
];

/// The items of the <pids> stack each column fetches (output.c setREL), of those a sort
/// may name.
pub(super) fn items(pr: Pr) -> &'static [Sr] {
    match pr {
        Pr::Agid => &[Sr::AutogrpId],
        Pr::Agnice => &[Sr::AutogrpNice],
        Pr::Args => &[Sr::Cmdline, Sr::Cmd],
        Pr::Bsdstart | Pr::Lstart | Pr::Start | Pr::Stime => &[Sr::TicsBegan],
        Pr::Bsdtime => &[Sr::TicsAll],
        Pr::C | Pr::Cp | Pr::Pcpu => &[Sr::TicsAll, Sr::TimeElapsed, Sr::Utilization],
        Pr::Cgname => &[Sr::Cgname],
        Pr::Cgroup => &[Sr::Cgroup],
        Pr::Cgroupns => &[Sr::NsCgroup],
        Pr::Class | Pr::Sched => &[Sr::SchedClass],
        Pr::Comm => &[Sr::Cmd, Sr::Cmdline],
        Pr::Context | Pr::Procs => &[Sr::IdTgid],
        Pr::Drs | Pr::Dsiz | Pr::Trs | Pr::Tsiz => &[Sr::VsizeBytes, Sr::AddrCodeEnd, Sr::AddrCodeStart],
        Pr::Egid => &[Sr::IdEgid],
        Pr::Egroup => &[Sr::IdEgroup, Sr::IdEgid],
        Pr::Eip => &[Sr::AddrCurrEip],
        Pr::Esp => &[Sr::AddrCurrEsp],
        Pr::Etime | Pr::Etimes => &[Sr::TimeElapsed],
        Pr::Euid => &[Sr::IdEuid],
        Pr::Euser => &[Sr::IdEuser, Sr::IdEuid],
        Pr::Exe => &[Sr::Exe],
        Pr::Fgid => &[Sr::IdFgid],
        Pr::Fgroup => &[Sr::IdFgroup, Sr::IdFgid],
        Pr::Flag => &[Sr::Flags],
        Pr::Fname => &[Sr::Cmd],
        Pr::Fuid => &[Sr::IdFuid],
        Pr::Fuser => &[Sr::IdFuser, Sr::IdFuid],
        Pr::Ipcns => &[Sr::NsIpc],
        Pr::Lim => &[Sr::RssRlim],
        Pr::Luid => &[Sr::IdLogin],
        Pr::Lxcname => &[Sr::Lxcname],
        Pr::Majflt => &[Sr::FltMaj],
        Pr::Minflt => &[Sr::FltMin],
        Pr::Mntns => &[Sr::NsMnt],
        Pr::Netns => &[Sr::NsNet],
        Pr::Nice => &[Sr::Nice, Sr::SchedClass],
        Pr::Nlwp => &[Sr::Nlwp],
        Pr::Nop => &[Sr::Noop],
        Pr::Numa => &[Sr::ProcessorNode],
        Pr::Oom => &[Sr::OomScore],
        Pr::OomAdj => &[Sr::OomAdj],
        Pr::Opri | Pr::Pri | Pr::PriApi | Pr::PriBar | Pr::PriBaz | Pr::PriFoo | Pr::Priority => {
            &[Sr::Priority]
        }
        Pr::Pgid => &[Sr::IdPgrp],
        Pr::Pidns => &[Sr::NsPid],
        Pr::Pmem | Pr::Rss => &[Sr::VmRss],
        Pr::Ppid => &[Sr::IdPpid],
        Pr::Psr => &[Sr::Processor],
        Pr::Pss => &[Sr::SmapPss],
        Pr::Rbytes => &[Sr::IoReadBytes],
        Pr::Rchars => &[Sr::IoReadChars],
        Pr::Rgid => &[Sr::IdRgid],
        Pr::Rgroup => &[Sr::IdRgroup, Sr::IdRgid],
        Pr::Rops => &[Sr::IoReadOps],
        Pr::Rtprio => &[Sr::SchedClass, Sr::PriorityRt],
        Pr::Ruid => &[Sr::IdRuid],
        Pr::Ruser => &[Sr::IdRuser, Sr::IdRuid],
        Pr::S => &[Sr::State],
        Pr::SdMachine => &[Sr::SdMach],
        Pr::SdOuid => &[Sr::SdOuid],
        Pr::SdSeat => &[Sr::SdSeat],
        Pr::SdSession => &[Sr::SdSess],
        Pr::SdSlice => &[Sr::SdSlice],
        Pr::SdUnit => &[Sr::SdUnit],
        Pr::SdUunit => &[Sr::SdUunit],
        Pr::Sess => &[Sr::IdSession],
        Pr::SgiP => &[Sr::State, Sr::Processor],
        Pr::Sgid => &[Sr::IdSgid],
        Pr::Sgroup => &[Sr::IdSgroup, Sr::IdSgid],
        Pr::Sig => &[Sr::Signals],
        Pr::Sigcatch => &[Sr::Sigcatch],
        Pr::Sigignore => &[Sr::Sigignore],
        Pr::Sigmask => &[Sr::Sigblocked],
        Pr::Size => &[Sr::VsizeBytes],
        Pr::Stackp => &[Sr::AddrStackStart],
        Pr::Stat => &[
            Sr::State,
            Sr::Nice,
            Sr::VmRssLocked,
            Sr::IdSession,
            Sr::IdTgid,
            Sr::Nlwp,
            Sr::IdPgrp,
            Sr::IdTpgid,
        ],
        Pr::Suid => &[Sr::IdSuid],
        Pr::Supgid => &[Sr::Supgids],
        Pr::Supgrp => &[Sr::Supgroups],
        Pr::Suser => &[Sr::IdSuser, Sr::IdSuid],
        Pr::Swapable => &[Sr::VmData, Sr::VmStack, Sr::VsizeBytes],
        Pr::Sz | Pr::Vsz => &[Sr::VmSize],
        Pr::TLeft | Pr::TLeft2 | Pr::TRight | Pr::TRight2 | Pr::TUnlimited | Pr::TUnlimited2 | Pr::Tty4 => {
            &[]
        }
        Pr::Tasks => &[Sr::IdPid],
        Pr::Time | Pr::Times => &[Sr::TimeAll],
        Pr::Timens => &[Sr::NsTime],
        Pr::Tpgid => &[Sr::IdTpgid],
        Pr::Tsig => &[Sr::Sigpending],
        Pr::Tty8 => &[Sr::TtyName],
        Pr::Userns => &[Sr::NsUser],
        Pr::Uss => &[Sr::SmapPrvTotal],
        Pr::Utilization => &[Sr::Utilization],
        Pr::UtilizationC => &[Sr::UtilizationC],
        Pr::Utsns => &[Sr::NsUts],
        Pr::Wbytes => &[Sr::IoWriteBytes],
        Pr::Wcbytes => &[Sr::IoWriteCbytes],
        Pr::Wchan => &[Sr::WchanName],
        Pr::Wchars => &[Sr::IoWriteChars],
        Pr::Wops => &[Sr::IoWriteOps],
    }
}

/// search_format_array.
pub(super) fn spec(name: &[u8]) -> Option<&'static Spec> {
    SPECS.iter().find(|s| s.spec.as_bytes() == name)
}

/// search_macro_array.
pub(super) fn macro_list(name: &[u8]) -> Option<&'static str> {
    MACROS
        .iter()
        .find(|(m, _)| m.as_bytes() == name)
        .map(|&(_, list)| list)
}
