// Writes crates/cmdline/src/tables.rs: the character classes the Docker CLI formats text
// with, taken from the code it is built with rather than from Unicode's files, so that
// they match it rune for rune. `generate`, beside this file, runs it inside a docker/cli
// checkout, whose vendored packages it imports.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"unicode"

	"github.com/mattn/go-runewidth"
	"golang.org/x/text/width"
)

// table prints the runes for which in is true as a sorted list of inclusive ranges.
func table(name string, doc []string, in func(r rune) bool) {
	fmt.Println()
	for _, line := range doc {
		fmt.Printf("/// %s\n", line)
	}
	fmt.Printf("pub(crate) static %s: &[(u32, u32)] = &[\n", name)
	start := rune(-1)
	for r := rune(0); r <= unicode.MaxRune+1; r++ {
		inside := r <= unicode.MaxRune && in(r)
		if inside && start < 0 {
			start = r
		}
		if !inside && start >= 0 {
			fmt.Printf("    (0x%X, 0x%X),\n", start, r-1)
			start = -1
		}
	}
	fmt.Println("];")
}

func main() {
	version := strings.TrimPrefix(runtime.Version(), "go")
	fmt.Printf("//! Generated by scripts/cmdline-tables from docker/cli v29.8.1 built with Go %s,\n", version)
	fmt.Println("//! go-runewidth v0.0.29 and golang.org/x/text v0.42.0 (Unicode 15.0.0). Do not edit.")

	table("NOT_PRINT", []string{
		"Runes from U+0080 up that Go's `strconv.IsPrint` rejects, which `strconv.Quote` escapes.",
	}, func(r rune) bool { return r >= 0x80 && !strconv.IsPrint(r) })

	table("WIDE", []string{
		"East Asian Wide and Fullwidth runes, as golang.org/x/text/width classes them: two",
		"columns to the CLI's `Ellipsis`.",
	}, func(r rune) bool {
		k := width.LookupRune(r).Kind()
		return k == width.EastAsianWide || k == width.EastAsianFullwidth
	})

	// The CLI's tables use go-runewidth's DefaultCondition, whose EastAsianWidth follows
	// the locale (RUNEWIDTH_EASTASIAN, LC_ALL, LC_CTYPE, LANG).
	narrow := &runewidth.Condition{EastAsianWidth: false, StrictEmojiNeutral: true}
	eastAsian := &runewidth.Condition{EastAsianWidth: true, StrictEmojiNeutral: true}
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if (narrow.RuneWidth(r) == 0) != (eastAsian.RuneWidth(r) == 0) {
			panic(fmt.Sprintf("U+%04X has no width in one locale only", r))
		}
	}
	table("ZERO", []string{
		"Runes go-runewidth gives no column, in any locale.",
	}, func(r rune) bool { return narrow.RuneWidth(r) == 0 })
	table("DOUBLE", []string{
		"Runes go-runewidth gives two columns outside an East Asian locale.",
	}, func(r rune) bool { return narrow.RuneWidth(r) == 2 })
	table("DOUBLE_EAST_ASIAN", []string{
		"Runes go-runewidth gives two columns in an East Asian locale.",
	}, func(r rune) bool { return eastAsian.RuneWidth(r) == 2 })

	// Go's words for Linux's errors (syscall.Errno.Error), which runc's messages carry.
	// This Go runs on the build host, so its tables are read from the source.
	arm64 := errnos("zerrors_linux_arm64.go")
	amd64 := errnos("zerrors_linux_amd64.go")
	for n, text := range amd64 {
		if arm64[n] != text {
			panic(fmt.Sprintf("errno %d differs between arm64 and amd64", n))
		}
	}
	fmt.Println()
	fmt.Println("/// Linux's errors in Go's words (syscall.Errno.Error, zerrors_linux_*.go), by number;")
	fmt.Println("/// the last only on arm64, where Go has a word for it.")
	fmt.Println("pub(crate) static LINUX_ERRNO: &[(i32, &str, bool)] = &[")
	for n := 1; n < 4096; n++ {
		text, ok := arm64[n]
		if !ok {
			continue
		}
		_, both := amd64[n]
		fmt.Printf("    (%d, %s, %t),\n", n, strconv.Quote(text), both)
	}
	fmt.Println("];")
}

// errnos reads the `errors` table of Go's syscall source file `name`.
func errnos(name string) map[int]string {
	src, err := os.ReadFile(filepath.Join(runtime.GOROOT(), "src", "syscall", name))
	if err != nil {
		panic(err)
	}
	block := regexp.MustCompile(`(?s)var errors = \[\.\.\.\]string\{(.*?)\n\}`).FindSubmatch(src)
	if block == nil {
		panic("no errors table in " + name)
	}
	out := map[int]string{}
	for _, m := range regexp.MustCompile(`(?m)^\s*(\d+):\s*("(?:[^"\\]|\\.)*"),`).FindAllSubmatch(block[1], -1) {
		n, _ := strconv.Atoi(string(m[1]))
		text, err := strconv.Unquote(string(m[2]))
		if err != nil {
			panic(err)
		}
		out[n] = text
	}
	return out
}
