"""What the Agent Skills reference validator (skills-ref) makes of each skill directory
under the roots given: its errors, as `validate` lists them, and its frontmatter as
strictyaml reads it; and Python's own
`str.isalnum`, as code point ranges, which shards' validator reads names with."""
import json
import os
import sys
from pathlib import Path

import strictyaml
from skills_ref.validator import validate


def frontmatter(skill_dir):
    """The frontmatter as strictyaml reads it, as skills-ref's parse_frontmatter takes it:
    the text between the first two `---`; None where it reads none."""
    for name in ("SKILL.md", "skill.md"):
        path = skill_dir / name
        if path.exists():
            content = path.read_text()
            break
    else:
        return None
    if not content.startswith("---"):
        return None
    parts = content.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        return strictyaml.load(parts[1]).data
    except strictyaml.YAMLError:
        return None

out_answers, out_tables, *roots = sys.argv[1:]
answers = {}
for root in roots:
    base = Path(root)
    for d in sorted(os.listdir(base)):
        if not (base / d).is_dir():
            continue
        answers[f"{base.name}/{d}"] = {
            "errors": validate(base / d),
            "frontmatter": frontmatter(base / d),
        }
with open(out_answers, "w", encoding="utf-8") as f:
    json.dump(answers, f, indent=1, ensure_ascii=False, sort_keys=True)
    f.write("\n")

ranges = []
for c in range(0x110000):
    if 0xD800 <= c <= 0xDFFF:
        continue
    if chr(c).isalnum():
        if ranges and ranges[-1][1] == c - 1:
            ranges[-1][1] = c
        else:
            ranges.append([c, c])
import unicodedata
with open(out_tables, "w", encoding="utf-8") as f:
    f.write("//! Python's `str.isalnum` (Python %s, Unicode %s), as code point ranges, for skill\n" % (sys.version.split()[0], unicodedata.unidata_version))
    f.write("//! names as the reference validator reads them. Generated by scripts/skills/generate.\n\n")
    f.write("pub const ALNUM: &[(u32, u32)] = &[\n")
    for lo, hi in ranges:
        f.write("    (0x%X, 0x%X),\n" % (lo, hi))
    f.write("];\n")
