[package]
name = "shards"
version = "0.1.0"
description = "shards: microVMs for agents, designed for home or at scale"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
shards-abi = { path = "../abi" }
shards-vmm = { path = "../vmm" }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
sha2 = "0.10"
shards-image = { path = "../image" }
shards-testguest = { path = "../testguest" }

[[bench]]
name = "boot"
harness = false

[[bench]]
name = "restore"
harness = false

[[bench]]
name = "firecracker"
harness = false
