[package]
name = "shards"
version = "0.1.0"
description = "shards: rootless microVMs you build and run like containers"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
libc = "0.2"
shards-vmm = { path = "../vmm" }

[dev-dependencies]
shards-testguest = { path = "../testguest" }
